spring:
  main:
    web-application-type: none
  kafka:
    consumer:
      group-id: consumer
      bootstrap-servers:
      - localhost:9092
      - localhost:9192
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.formation.model.JsonDeserializer
        
    listener:
      concurrency: 3 

      
      
      
#logging:
#  file:
#    name: consume.log
#    path: .